const countryList = [
    { chinese: "阿富汗", english: "Afghanistan" },
    { chinese: "巴林", english: "Bahrain" },
    { chinese: "孟加拉國", english: "Bangladesh" },
    { chinese: "白俄羅斯", english: "Belarus" },
    { chinese: "波斯尼亞和黑塞哥維那", english: "Bosnia and Herzegovina" },
    { chinese: "博茨瓦納", english: "Botswana" },
    { chinese: "巴西", english: "Brazil" },
    { chinese: "赤道幾內亞", english: "Equatorial Guinea" },
    { chinese: "埃及", english: "Egypt" },
    { chinese: "薩爾瓦多", english: "El Salvador" },
    { chinese: "伊索比亞", english: "Ethiopia" },
    { chinese: "甘比亞", english: "Gambia" },
    { chinese: "德國", english: "Germany" },
    { chinese: "瓜地馬拉", english: "Guatemala" },
    { chinese: "印度", english: "India" },
    { chinese: "印尼", english: "Indonesia" },
    { chinese: "伊朗", english: "Iran" },
    { chinese: "伊拉克", english: "Iraq" },
    { chinese: "以色列", english: "Israel" },
    { chinese: "日本", english: "Japan" },
    { chinese: "約旦", english: "Jordan" },
    { chinese: "科威特", english: "Kuwait" },
    { chinese: "吉爾吉斯", english: "Kyrgyzstan" },
    { chinese: "利比亞", english: "Libya" },
    { chinese: "列支敦士登", english: "Liechtenstein" },
    { chinese: "盧旺達", english: "Rwanda" },
    { chinese: "聖基茨和尼維斯", english: "Saint Kitts and Nevis" },
    { chinese: "沙特阿拉伯", english: "Saudi Arabia" },
    { chinese: "塞爾維亞", english: "Serbia" },
    { chinese: "新加坡", english: "Singapore" },
    { chinese: "斯洛伐克", english: "Slovakia" },
    { chinese: "索馬里", english: "Somalia" },
    { chinese: "南蘇丹", english: "South Sudan" },
    { chinese: "蘇丹", english: "Sudan" },
    { chinese: "敘利亞", english: "Syria" },
    { chinese: "泰國", english: "Thailand" },
    { chinese: "特立尼達和多巴哥", english: "Trinidad and Tobago" },
    { chinese: "突尼斯", english: "Tunisia" },
    { chinese: "阿拉伯聯合大公國", english: "United Arab Emirates" },
    { chinese: "美國", english: "United States" },
    { chinese: "越南", english: "Vietnam" },
    { chinese: "葉門", english: "Yemen" },
    { chinese: "贊比亞", english: "Zambia" }
];

let countries = JSON.parse(localStorage.getItem('countries')) || [
    { name: "委內瑞拉", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1863年廢除死刑" },
    { name: "聖馬利諾", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1865年廢除死刑" },
    { name: "哥斯大黎加", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1877年廢除死刑" },
    { name: "葡屬澳門", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1886年廢除死刑" },
    { name: "巴拿馬", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1903年廢除死刑" },
    { name: "厄瓜多", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1906年廢除死刑" },
    { name: "烏拉圭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1907年廢除死刑" },
    { name: "哥倫比亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1910年廢除死刑" },
    { name: "冰島", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1928年廢除死刑" },
    { name: "德國（西德）", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1949年廢除死刑" },
    { name: "宏都拉斯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1956年廢除死刑" },
    { name: "摩納哥", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1962年廢除死刑" },
    { name: "多明尼加", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1966年廢除死刑" },
    { name: "奧地利", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1968年廢除死刑" },
    { name: "梵蒂岡", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1969年廢除死刑" },
    { name: "芬蘭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1972年廢除死刑" },
    { name: "瑞典", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1973年廢除死刑" },
    { name: "加拿大", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1976年廢除死刑" },
    { name: "葡萄牙", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1976年廢除死刑" },
    { name: "丹麥", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1978年廢除死刑" },
    { name: "索羅門群島", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1978年廢除死刑" },
    { name: "吐瓦魯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1978年廢除死刑" },
    { name: "吉里巴斯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1979年廢除死刑" },
    { name: "盧森堡", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1979年廢除死刑" },
    { name: "尼加拉瓜", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1979年廢除死刑" },
    { name: "挪威", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1979年廢除死刑" },
    { name: "萬那杜", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1980年廢除死刑" },
    { name: "維德角", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1981年廢除死刑" },
    { name: "法國", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1981年廢除死刑" },
    { name: "荷蘭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1982年廢除死刑" },
    { name: "澳洲", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1985年廢除死刑" },
    { name: "馬紹爾群島", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1986年廢除死刑" },
    { name: "密克羅尼西亞聯邦", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1986年廢除死刑" },
    { name: "海地", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1987年廢除死刑" },
    { name: "列支敦斯登", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1987年廢除死刑" },
    { name: "東德", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1987年廢除死刑" },
    { name: "柬埔寨", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1989年廢除死刑" },
    { name: "紐西蘭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1989年廢除死刑" },
    { name: "安道爾", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "捷克斯洛伐克", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "匈牙利", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "愛爾蘭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "莫三比克", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "納米比亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "羅馬尼亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "聖多美普林西比", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1990年廢除死刑" },
    { name: "克羅埃西亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1991年廢除死刑" },
    { name: "北馬其頓", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1991年廢除死刑" },
    { name: "斯洛維尼亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1991年廢除死刑" },
    { name: "安哥拉", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1992年廢除死刑" },
    { name: "巴拉圭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1992年廢除死刑" },
    { name: "瑞士", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1992年廢除死刑" },
    { name: "幾內亞比索", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1993年廢除死刑" },
    { name: "塞席爾", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1993年廢除死刑" },
    { name: "英屬香港", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1993年廢除死刑" },
    { name: "義大利", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1994年廢除死刑" },
    { name: "帛琉", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1994年廢除死刑" },
    { name: "吉布地", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1995年廢除死刑" },
    { name: "模里西斯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1995年廢除死刑" },
    { name: "南非", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1995年廢除死刑" },
    { name: "西班牙", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1995年廢除死刑" },
    { name: "塞爾維亞與蒙特內哥羅", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1995年廢除死刑" },
    { name: "比利時", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1996年廢除死刑" },
    { name: "尼泊爾", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1997年廢除死刑" },
    { name: "波蘭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1997年廢除死刑" },
    { name: "亞美尼亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1998年廢除死刑" },
    { name: "亞塞拜然", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1998年廢除死刑" },
    { name: "保加利亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1998年廢除死刑" },
    { name: "愛沙尼亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1998年廢除死刑" },
    { name: "立陶宛", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1998年廢除死刑" },
    { name: "英國", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1998年廢除死刑" },
    { name: "土庫曼", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "1999年廢除死刑" },
    { name: "象牙海岸", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2000年廢除死刑" },
    { name: "馬爾他", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2000年廢除死刑" },
    { name: "烏克蘭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2000年廢除死刑" },
    { name: "波赫", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2000年廢除死刑" },
    { name: "希臘", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2001年廢除死刑" },
    { name: "賽普勒斯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2002年廢除死刑" },
    { name: "東帝汶", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2002年廢除死刑" },
    { name: "不丹", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2004年廢除死刑" },
    { name: "薩摩亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2004年廢除死刑" },
    { name: "塞內加爾", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2004年廢除死刑" },
    { name: "土耳其", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2004年廢除死刑" },
    { name: "墨西哥", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2005年廢除死刑" },
    { name: "摩爾多瓦", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2005年廢除死刑" },
    { name: "喬治亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2006年廢除死刑" },
    { name: "菲律賓", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2006年廢除死刑" },
    { name: "阿爾巴尼亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2007年廢除死刑" },
    { name: "吉爾吉斯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2007年廢除死刑" },
    { name: "盧安達", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2007年廢除死刑" },
    { name: "烏茲別克", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2008年廢除死刑" },
    { name: "阿根廷", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2009年廢除死刑" },
    { name: "蒲隆地", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2009年廢除死刑" },
    { name: "多哥", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2009年廢除死刑" },
    { name: "玻利維亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2009年廢除死刑" },
    { name: "加彭", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2010年廢除死刑" },
    { name: "拉脫維亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2012年廢除死刑" },
    { name: "剛果共和國", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2015年廢除死刑" },
    { name: "斐濟", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2015年廢除死刑" },
    { name: "馬達加斯加", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2015年廢除死刑" },
    { name: "蘇利南", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2015年廢除死刑" },
    { name: "貝南", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2016年廢除死刑" },
    { name: "諾魯", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2016年廢除死刑" },
    { name: "幾內亞", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2017年廢除死刑" },
    { name: "蒙古國", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2017年廢除死刑" },
    { name: "查德", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2020年廢除死刑" },
    { name: "哈薩克", status: "否", deathPenaltyStatus: "廢除", additionalInfo: "2021年廢除死刑" },
    { name: "馬爾地夫", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1965年停止執行死刑" },
    { name: "諾魯", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1968年停止執行死刑" },
    { name: "巴布亞紐幾內亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1975年停止執行死刑" },
    { name: "斯里蘭卡", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1976年停止執行死刑" },
    { name: "尼日", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1976年停止執行死刑" },
    { name: "格瑞那達", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1978年停止執行死刑" },
    { name: "馬利", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1980年停止執行死刑" },
    { name: "中非", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1981年停止執行死刑" },
    { name: "東加", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1982年停止執行死刑" },
    { name: "史瓦帝尼", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1983年停止執行死刑" },
    { name: "汶萊", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1984年停止執行死刑" },
    { name: "巴貝多", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1984年停止執行死刑" },
    { name: "貝里斯", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1985年停止執行死刑" },
    { name: "多米尼克", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1986年停止執行死刑" },
    { name: "肯亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1987年停止執行死刑" },
    { name: "茅利塔尼亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1987年停止執行死刑" },
    { name: "布吉納法索", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1988年停止執行死刑" },
    { name: "牙買加", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1988年停止執行死刑" },
    { name: "寮國", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1989年停止執行死刑" },
    { name: "厄利垂亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1989年停止執行死刑" },
    { name: "突尼西亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1991年停止執行死刑" },
    { name: "安地卡及巴布達", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1991年停止執行死刑" },
    { name: "馬拉威", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1992年停止執行死刑" },
    { name: "摩洛哥", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1993年停止執行死刑" },
    { name: "阿爾及利亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1993年停止執行死刑" },
    { name: "迦納", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1993年停止執行死刑" },
    { name: "坦尚尼亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1994年停止執行死刑" },
    { name: "賴比瑞亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1995年停止執行死刑" },
    { name: "賴索托", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1995年停止執行死刑" },
    { name: "聖露西亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1995年停止執行死刑" },
    { name: "聖文森及格瑞那丁", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1995年停止執行死刑" },
    { name: "俄羅斯", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1996年停止執行死刑" },
    { name: "喀麥隆", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1997年停止執行死刑" },
    { name: "葛摩", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1997年停止執行死刑" },
    { name: "大韓民國", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1997年停止執行死刑" },
    { name: "尚比亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1997年停止執行死刑" },
    { name: "蓋亞那", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1997年停止執行死刑" },
    { name: "獅子山", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1998年停止執行死刑" },
    { name: "千里達及托巴哥", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "1999年停止執行死刑" },
    { name: "巴哈馬", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2000年停止執行死刑" },
    { name: "瓜地馬拉", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2000年停止執行死刑" },
    { name: "幾內亞", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2001年停止執行死刑" },
    { name: "剛果民主共和國", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2003年停止執行死刑" },
    { name: "卡達", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2003年停止執行死刑" },
    { name: "古巴", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2003年停止執行死刑" },
    { name: "黎巴嫩", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2004年停止執行死刑" },
    { name: "塔吉克", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2004年停止執行死刑" },
    { name: "烏干達", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2005年停止執行死刑" },
    { name: "辛巴威", status: "否", deathPenaltyStatus: "實質廢除", additionalInfo: "2005年停止執行死刑" }
];
